//! Standalone Becke partitioning implementation for DFT numerical integration.
//!
//! This file is intended not to interfere to other parts of the codebase.
//!
//! This code tries to somehow optimize with SIMD. However, this requires manually setting
//! `target-cpu` or something similar when cargo build (only release is not enough). The efficiency
//! is not tested currently, but theoretically should not be too pitiful I believe.

use itertools::Itertools;
use libcint::gto::deriv_util::FpSimd;
use rayon::prelude::*;

const SIMDD: usize = 8;

const SIMD_0: f64simd = f64simd::splat(0.0);
const SIMD_1_0: f64simd = f64simd::splat(1.0);
const SIMD_0_5: f64simd = f64simd::splat(0.5);
const SIMD_1_5: f64simd = f64simd::splat(1.5);

#[allow(non_camel_case_types)]
type f64simd = FpSimd<f64, SIMDD>;

/// Becke partitioning implementation for DFT numerical integration.
///
/// # Arguments
///
/// - `grid_coords`: A slice of 3D coordinates representing the grid points. Length `ngrids`.
/// - `atom_coords`: A slice of 3D coordinates representing the atomic positions. Length `natm`.
/// - `atm_indices`: A slice of indices mapping each grid point to its corresponding atom (that
///   generates the Lebedev angular grids). Length `ngrids`. Usually values should not exceed `natm
///   - 1`, but will treat as padding atom if exceeds.
/// - `quadrature_weights`: A slice of original quadrature weights (generated by Lebedev angular
///   quadrature) for each grid point. Length `ngrids`.
/// - `adjustment_factor`: A slice of adjustment factors (usually adjusted by atomic radii) for each
///   grid point. Shape `(natm, natm)`, flattened. cf Becke 1988 eqs (A2, A5).
///   - **Note**: this pairwise matrix is anti-symmetric, in column-major order. If you use this
///     function with row-major, you may need to first transpose it.
/// - `hardness`: Cutoff hardness of screen function. cf Becke 1988 eq (20) and FIG 1. Most commonly
///   used value is 3, and we have manually dispatched the case of 3 in code implementation.
/// - `nbatch`: Batch size for parallel processing. Must be a multiple of `SIMDD` (8 for AVX-512).
///
/// # Reference
///
/// A multicenter numerical integration scheme for polyatomic molecules
/// A. D. Becke
/// J. Chem. Phys. 88, 2547 (1988), doi: 10.1063/1.454033
pub fn becke_partition(
    grid_coords: &[[f64; 3]],
    atm_coords: &[[f64; 3]],
    atm_indices: &[usize],
    quadrature_weights: &[f64],
    adjustment_factor: &[f64],
    hardness: usize,
    nbatch: usize,
) -> Vec<f64> {
    // dimensions
    let ngrids = grid_coords.len();
    let natm = atm_coords.len();
    assert!(nbatch % SIMDD == 0, "nbatch must be a multiple of {SIMDD}");
    assert!(adjustment_factor.len() == natm * natm, "adjustment_factor must have length natm * natm");
    assert!(atm_indices.len() == ngrids, "atm_indices must have length ngrids");
    assert!(quadrature_weights.len() == ngrids, "quadrature_weights must have length ngrids");

    let adjustment_factor = adjustment_factor.chunks_exact(natm).collect_vec();

    // generate atom_dist before iteration to grid coordinates
    // since it is not bottleneck, we duplicate the calculation for A > B.
    let atom_dist: Vec<f64> = (0..natm * natm)
        .into_par_iter()
        .map(|idx| {
            let (A, B) = (idx / natm, idx % natm);
            if A == B {
                f64::INFINITY
            } else {
                dist3_naive(&atm_coords[A], &atm_coords[B])
            }
        })
        .collect();
    let atom_dist = atom_dist.chunks_exact(natm).collect_vec();

    // prepare output buffer for partition weights
    let weights = vec![0.0; ngrids];

    // par-iter over grid coordinates in batches
    let ntasks = ngrids.div_ceil(nbatch);
    (0..ntasks).into_par_iter().for_each(|itask| {
        let g0 = itask * nbatch;
        let g1 = (g0 + nbatch).min(ngrids);
        let nlane = (g1 - g0).div_ceil(SIMDD);

        // batched vectors preparation
        let mut coords = vec![[SIMD_0; 3]; nlane];
        let mut wquad = vec![SIMD_0; nlane];
        let mut atm_idx = vec![[0; SIMDD]; nlane];
        for lane in 0..nlane {
            let glane = g0 + lane * SIMDD;
            for g in 0..SIMDD {
                if glane + g < g1 {
                    for t in 0..3 {
                        coords[lane][t][g] = grid_coords[glane + g][t];
                    }
                    wquad[lane][g] = quadrature_weights[glane + g];
                    atm_idx[lane][g] = atm_indices[glane + g];
                } else {
                    // padding atom index set to natm (out of range)
                    atm_idx[lane][g] = natm;
                }
            }
        }

        for lane in 0..nlane {
            // partition output for this batch
            let mut P = vec![SIMD_1_0; natm];

            // evaluate grid distance to atom for this lane
            let mut dist = vec![SIMD_0; natm];
            for A in 0..natm {
                dist[A] = dist3_hybrid(&coords[lane], &atm_coords[A]);
            }

            // 1st pass: evaluate Becke partition function
            for A in 0..natm {
                for B in 0..A {
                    let a_factor = adjustment_factor[B][A]; // column-major order
                    let mu = (dist[A] - dist[B]) / f64simd::splat(atom_dist[A][B]);
                    let f3 = match hardness {
                        3 => switch_f3(mu, a_factor),
                        _ => switch_f_hardness(mu, a_factor, hardness),
                    };
                    P[A] *= SIMD_0_5 * (SIMD_1_0 - f3);
                    P[B] *= SIMD_0_5 * (SIMD_1_0 + f3);
                }
            }

            // compute partition function and weights
            let mut Pg = SIMD_0;
            let mut Z = SIMD_0;
            for A in 0..natm {
                Z += P[A];
                let mask = atm_idx[lane].map(|a| a == A);
                Pg = P[A].mask_select(mask, Pg);
            }
            let partition = Pg / Z;
            let w = wquad[lane] * partition;

            // write back to output buffer
            let g_start = g0 + lane * SIMDD;
            let g_end = (g_start + SIMDD).min(g1);
            let weights = unsafe { cast_mut_slice(&weights[g_start..g_end]) };
            for g in 0..(g_end - g_start) {
                weights[g] = w[g];
            }
        }
    });

    weights
}

/* #region simple utilities */

fn dist3_naive(a: &[f64; 3], b: &[f64; 3]) -> f64 {
    let dx = a[0] - b[0];
    let dy = a[1] - b[1];
    let dz = a[2] - b[2];
    (dx * dx + dy * dy + dz * dz).sqrt()
}

fn dist3_hybrid(a: &[f64simd; 3], b: &[f64; 3]) -> f64simd {
    let dx = a[0] - f64simd::splat(b[0]);
    let dy = a[1] - f64simd::splat(b[1]);
    let dz = a[2] - f64simd::splat(b[2]);
    (dx * dx + dy * dy + dz * dz).map(f64::sqrt)
}

/* #endregion */

/* #region switch function utilities */

fn switch_f3(mu: f64simd, a_factor: f64) -> f64simd {
    let a_factor = f64simd::splat(a_factor);
    let nu = mu + a_factor * (SIMD_1_0 - mu * mu); // eq (A2)
    let f1 = (SIMD_1_5 - SIMD_0_5 * nu * nu) * nu; // eq (19)
    let f2 = (SIMD_1_5 - SIMD_0_5 * f1 * f1) * f1; // eq (19)
    let f3 = (SIMD_1_5 - SIMD_0_5 * f2 * f2) * f2; // eq (19)
    f3
}

fn switch_f_hardness(mu: f64simd, a_factor: f64, hardness: usize) -> f64simd {
    let a_factor = f64simd::splat(a_factor);
    let nu = mu + a_factor * (SIMD_1_0 - mu * mu); // eq (A2)
    let mut f = nu;
    for _ in 0..hardness {
        f = (SIMD_1_5 - SIMD_0_5 * f * f) * f; // eq (19)
    }
    f
}

/* #endregion */

/* #region enhancement to FpSimd */

trait FpSimdMaskAPI {
    fn mask_select(self, mask: [bool; SIMDD], other: Self) -> Self;
}

impl FpSimdMaskAPI for f64simd {
    fn mask_select(self, mask: [bool; SIMDD], other: Self) -> Self {
        let mut result = self;
        for i in 0..SIMDD {
            match mask[i] {
                true => result[i] = self[i],
                false => result[i] = other[i],
            }
        }
        result
    }
}

/* #endregion */

/* #region other utilities */

#[allow(clippy::mut_from_ref)]
unsafe fn cast_mut_slice<T>(slc: &[T]) -> &mut [T] {
    let len = slc.len();
    let ptr = slc.as_ptr() as *mut T;
    unsafe { std::slice::from_raw_parts_mut(ptr, len) }
}

/* #endregion */
