"""Analytical second derivative of the Becke partition weight w_g w.r.t. atomic
coordinates:  d2 w_g / dR_G dR_H.

This document is generated by AI. Its correctness has not been verified.

Equation tags continue from 10-2-becke_partition_deriv1.ipynb (ended at eq (8)).
This file holds BOTH the numerical reference (FD of PySCF get_dweight_dA) and
the analytical implementation, plus validation.

Run:  python 10-3-becke_partition_deriv2.py
"""
import numpy as np
from pyscf import gto, dft, hessian, data

XYZ0 = """
N  0   0   0
H  1.0 0.1 0.2
H  0.3 1.1 0.2
H  0.1 0.1 1.2
"""
BASIS = "def2-TZVP"


def get_mol_grids(xyz):
    mol = gto.Mole(atom=xyz, basis=BASIS, max_memory=32000).build()
    grids = dft.grid.Grids(mol).build()
    return mol, grids


def _shift_atom(xyz_str, atm, axis, delta):
    lines = xyz_str.strip().split("\n")
    parts = lines[atm].split()
    parts[1 + axis] = f"{float(parts[1 + axis]) + delta:.10f}"
    lines[atm] = "  ".join(parts)
    return "\n".join(lines) + "\n"


# ===========================================================================
# Numerical reference: finite-difference of PySCF get_dweight_dA
# ===========================================================================
def _dweight_dA_at(xyz_str):
    mol, grids = get_mol_grids(xyz_str)
    return hessian.rks.get_dweight_dA(mol, grids)


def numerical_d2weight_dAdB(xyz_str=XYZ0, h=5e-4 / data.nist.BOHR):
    """d2 w_g / dR_G dR_H via central FD of get_dweight_dA.  Shape (M,3,M,3,N)."""
    mol0, grids0 = get_mol_grids(xyz_str)
    natm = mol0.natm
    ngrids = grids0.coords.shape[0]
    d2 = np.zeros((natm, 3, natm, 3, ngrids))
    for H in range(natm):
        for b in range(3):
            dwp = _dweight_dA_at(_shift_atom(xyz_str, H, b, +h))
            dwm = _dweight_dA_at(_shift_atom(xyz_str, H, b, -h))
            d2[:, :, H, b, :] = (dwp - dwm) / (2 * h)
    return d2


# ===========================================================================
# Switch function: s, s', s''  (all wrt mu, via nu = mu + a(1-mu^2))
# ===========================================================================
def _switch_terms(nu, mu, a):
    """Return s, ds_dmu, d2s_dmu2 for s = 1/2(1 - f3(nu)), nu=mu+a(1-mu^2).

    Arrays broadcast over the grid axis.  p(x)=3/2 x - 1/2 x^3, p'=3/2(1-x^2),
    p''=-3x.
    """
    def p(x):
        return 1.5 * x - 0.5 * x ** 3
    def pp(x):
        return 1.5 * (1.0 - x * x)
    f1 = p(nu)
    f2 = p(f1)
    f3 = p(f2)
    s = 0.5 * (1.0 - f3)
    g0 = pp(nu)        # p'(nu)
    g1 = pp(f1)        # p'(f1)
    g2 = pp(f2)        # p'(f2)
    dnu = 1.0 - 2.0 * a * mu          # dnu/dmu
    d2nu = -2.0 * a                   # d2nu/dmu2
    Fprime = g2 * g1 * g0             # df3/dnu
    # eq (13): f3'' = -3 [ f2 (g1 g0)^2 + f1 g2 g0^2 + nu g2 g1 ]
    Fdouble = -3.0 * (f2 * (g1 * g0) ** 2 + f1 * g2 * g0 ** 2 + nu * g2 * g1)
    s_prime_nu = -0.5 * Fprime        # ds/dnu
    s_double_nu = -0.5 * Fdouble      # d2s/dnu2
    ds_dmu = s_prime_nu * dnu
    d2s_dmu2 = s_double_nu * dnu ** 2 + s_prime_nu * d2nu   # eq (14)
    return s, ds_dmu, d2s_dmu2


# ===========================================================================
# mu_{AB} = (r_A - r_B)/R_{AB} : first and second derivatives wrt atom coords
# ===========================================================================
def _mu_block(R_Ag, r_Ag, R_Bg, r_Bg, R_ABv_vec, R_AB, a_factor):
    """All first/second derivatives of mu_AB=(r_A-r_B)/R_AB at one grid point.

    Inputs (3,)-vectors and scalars for a single (A,B,g).
    Returns:
        mu,
        dmuA (3,), dmuB (3,)              dmu/dR_A , dmu/dR_B
        d2muAA (3,3), d2muAB (3,3), d2muBA (3,3), d2muBB (3,3)
    """
    r_A = r_Ag
    r_B = r_Bg
    uA = R_Ag / r_A                       # grid->A unit vec,  d r_A/d R_A = uA
    uB = R_Bg / r_B                       # grid->B unit vec
    R = R_AB
    Rn = R_ABv_vec                        # |R_AB|
    U = R / Rn                            # B->A unit vec, d R_AB/d R_A = U
    mu = (r_A - r_B) / Rn
    # --- first derivatives, eq (15) ---
    # dmu/dR_A = (uA - mu U)/Rn ;  dmu/dR_B = (-uB + mu U)/Rn
    dmuA = (uA - mu * U) / Rn
    dmuB = (-uB + mu * U) / Rn
    # --- second derivatives: quotient rule on f/g, f = r_A - r_B, g = Rn ---
    # d2mu/dX^i dY^j = [fXY*g - ((df/dX^i)(dg/dY^j) + (dg/dX^i)(df/dY^j))
    #                    - f*gXY] / g^2  +  2 f (dg/dX^i)(dg/dY^j) / g^3
    # First derivs of f, g:  df/dR_A = uA, df/dR_B = -uB ;  dg/dR_A = U, dg/dR_B = -U
    # Second derivs of f (Proj(v) = I - v v^T):
    #   d2f/dR_A^2  = +Proj(uA)/r_A ;  d2f/dR_B^2 = -Proj(uB)/r_B (sign: -r_B term)
    #   d2f/dR_A dR_B = 0
    # Second derivs of g = |R_A - R_B|:
    #   d2g/dR_A^2 = +Proj(U)/Rn ;  d2g/dR_B^2 = +Proj(U)/Rn ;  d2g/dR_A dR_B = -Proj(U)/Rn
    PA = np.eye(3) - np.outer(uA, uA)
    PB = np.eye(3) - np.outer(uB, uB)
    PU = np.eye(3) - np.outer(U, U)
    fAA = PA / r_A          # d2 r_A / dR_A^2 = +Proj(uA)/r_A
    fBB = -PB / r_B         # d2(-r_B)/dR_B^2 = -Proj(uB)/r_B  (sign!)
    fAB = np.zeros((3, 3))  # d2f/dR_A dR_B = 0
    gAA = PU / Rn
    gBB = PU / Rn
    gAB = -PU / Rn
    dfA = uA; dfB = -uB
    dgA = U;  dgB = -U
    f = r_A - r_B
    # d2mu/dX^i dY^j = [fXY*g - ((df/dX^i)(dg/dY^j) + (dg/dX^i)(df/dY^j)) - f*gXY]/g^2
    #                  + 2 f (dg/dX^i)(dg/dY^j) / g^3
    # i.e. symmetric cross term is outer(fX,gY) + outer(gX,fY)  (NOT outer(fY,gX)).
    def d2(fX, fY, fXY, gX, gY, gXY):
        return (fXY * Rn - (np.outer(fX, gY) + np.outer(gX, fY)) - f * gXY) / Rn ** 2 \
            + 2 * f * np.outer(gX, gY) / Rn ** 3
    d2AA = d2(dfA, dfA, fAA, dgA, dgA, gAA)
    d2AB = d2(dfA, dfB, fAB, dgA, dgB, gAB)
    d2BA = d2AB.T
    d2BB = d2(dfB, dfB, fBB, dgB, dgB, gBB)
    return mu, dmuA, dmuB, d2AA, d2AB, d2BA, d2BB


# ===========================================================================
# Analytical second derivative (reference, per-grid loop -- clarity first)
# ===========================================================================
def becke_weight_derivative2_ref(grid_coords, grid_weights, atm_coords, a_factor, atm_idx):
    """Per-grid reference implementation of d2 w_g/dR_G dR_H.

    Returns d2 (M,3,M,3,N) with the G==A_g (or H==A_g) rows left zero, to be
    filled by the interface via translation invariance (eq 8 of 10-2, applied
    to both derivative indices -- see notebook).
    """
    N = grid_coords.shape[0]
    M = atm_coords.shape[0]
    a_factor = np.array(a_factor, copy=True, dtype=float)
    np.fill_diagonal(a_factor, 0.0)
    d2 = np.zeros((M, 3, M, 3, N))

    arangeN = np.arange(N)
    for g in range(N):
        Ag = int(atm_idx[g])
        if Ag < 0:
            continue
        wb = grid_weights[g]
        rg = grid_coords[g]
        # precompute per-atom r_A, uA for this grid
        R_Ag = atm_coords - rg                       # (M,3)
        r_Ag = np.linalg.norm(R_Ag, axis=1)          # (M,)
        r_Ag_safe = np.where(r_Ag > 1e-14, r_Ag, 1.0)
        # atom-atom distances
        # build P_A = prod_{B!=A} s_AB; also need t_AB, v_AB=s''/s, and mu derivs
        # We'll compute per pair (A,B) with B!=A.
        # First gather pair data for all ordered pairs A!=B.
        # mu_AB etc:
        s = np.ones((M, M))      # s_AB (diag unused)
        t = np.zeros((M, M))     # t_AB = s'/s
        vv = np.zeros((M, M))    # v_AB = s''/s
        mu = np.zeros((M, M))
        dmu = {}                 # dmu[(A,B)] = (dmuA(3,), dmuB(3,))
        d2mu = {}                # d2mu[(A,B)] = (AA,AB,BA,BB) each (3,3)
        for A in range(M):
            for B in range(M):
                if A == B:
                    continue
                R_ABv = atm_coords[A] - atm_coords[B]
                Rn = np.linalg.norm(R_ABv)
                if Rn < 1e-14:
                    continue
                a = a_factor[A, B]
                muAB, dmuA, dmuB, hAA, hAB, hBA, hBB = _mu_block(
                    R_Ag[A], r_Ag[A], R_Ag[B], r_Ag[B], Rn, R_ABv, a)
                nu = muAB + a * (1.0 - muAB ** 2)
                # regularize: s<1e-14 -> treat t,v as 0 (matches C inv())
                if r_Ag[A] > 1e-14 and r_Ag[B] > 1e-14:
                    ss, ds, d2s = _switch_terms(np.array(nu), np.array(muAB), np.array(a))
                    ss = float(ss); ds = float(ds); d2s = float(d2s)
                    if ss > 1e-14:
                        tAB = ds / ss
                        vAB = d2s / ss
                    else:
                        tAB = 0.0
                        vAB = 0.0
                    s[A, B] = ss
                else:
                    # grid essentially on an atom (r_Ag or r_Bg < 1e-14): the unit
                    # vectors in _mu_block are ill-defined; regularize derivatives
                    # to zero (matches the inv() spirit). s_AB left at its init 1.0
                    # only affects P via this near-singular factor, which is 0/1 in
                    # the limit; for the test grids this branch never triggers.
                    s[A, B] = 1.0
                    tAB = 0.0; vAB = 0.0
                t[A, B] = tAB
                vv[A, B] = vAB
                mu[A, B] = muAB
                dmu[(A, B)] = (dmuA, dmuB)
                d2mu[(A, B)] = (hAA, hAB, hBA, hBB)
        # P_A = prod_{B!=A} s_AB
        P = np.ones(M)
        for A in range(M):
            for B in range(M):
                if B == A:
                    continue
                P[A] *= s[A, B]
        Sigma = P.sum()
        if Sigma < 1e-300:
            continue
        PA = P[Ag]
        q = PA / Sigma
        # --- dP_A/dR_G (eq 10) and d2P_A/dR_G dR_H (eq 11) for A = Ag ---
        # L1[G]  = d/dR_G ln P_A = sum_{B!=A} t_AB dmu_AB/dR_G      (eq 10)
        # L2[G,:,H,:] = d2/dR_G dR_H ln P_A, see eq (12)
        # dP_A/dR_G   = P_A * L1_G
        # d2P_A/dR_GdR_H = P_A * (L2_GH + L1_G L1_H)                (eq 11)
        Ag_local = Ag
        L1 = np.zeros((M, 3))
        L2 = np.zeros((M, 3, M, 3))
        for B in range(M):
            if B == Ag_local:
                continue
            # factor s_{Ag,B}; derivatives wrt endpoints Ag, B
            dmuA, dmuB = dmu[(Ag_local, B)]
            tAB = t[Ag_local, B]
            vAB = vv[Ag_local, B]
            hAA, hAB, hBA, hBB = d2mu[(Ag_local, B)]
            L1[Ag_local] += tAB * dmuA          # eq (10), A-role
            L1[B] += tAB * dmuB                 # eq (10), B-role
            w = vAB - tAB ** 2                  # eq (12): d2 ln s / dmu^2
            # endpoint combos: (Ag,Ag)->AA, (Ag,B)->AB, (B,Ag)->BA, (B,B)->BB
            pairs = [(Ag_local, Ag_local, dmuA, dmuA, hAA),
                     (Ag_local, B, dmuA, dmuB, hAB),
                     (B, Ag_local, dmuB, dmuA, hBA),
                     (B, B, dmuB, dmuB, hBB)]
            for (X, Y, dX, dY, hXY) in pairs:
                L2[X, :, Y, :] += w * np.outer(dX, dY) + tAB * hXY   # eq (12)
        dPA = PA * L1                                          # eq (10) -> dP_A/dR_G
        d2PA = PA * (L2 + np.einsum("gi,hj->gihj", L1, L1))  # eq (11)
        # --- Sigma derivatives: eq (16), sum over B of dP_B, d2P_B ---
        dSig = np.zeros((M, 3))
        d2Sig = np.zeros((M, 3, M, 3))
        for B in range(M):
            # ln P_B = sum_{C!=B} ln s_{B,C}
            L1B = np.zeros((M, 3))
            L2B = np.zeros((M, 3, M, 3))
            for C in range(M):
                if C == B:
                    continue
                dmuA, dmuB = dmu[(B, C)]
                tBC = t[B, C]; vBC = vv[B, C]
                hAA, hAB, hBA, hBB = d2mu[(B, C)]
                L1B[B] += tBC * dmuA
                L1B[C] += tBC * dmuB
                w = vBC - tBC ** 2
                pairs = [(B, B, dmuA, dmuA, hAA),
                         (B, C, dmuA, dmuB, hAB),
                         (C, B, dmuB, dmuA, hBA),
                         (C, C, dmuB, dmuB, hBB)]
                for (X, Y, dX, dY, hXY) in pairs:
                    L2B[X, :, Y, :] += w * np.outer(dX, dY) + tBC * hXY
            dSig += P[B] * L1B
            d2Sig += P[B] * (L2B + np.einsum("gi,hj->gihj", L1B, L1B))
        # --- assemble d2 q = d2 (P_A/Sigma), eq (9) ---
        # d2q_GH = (d2PA_GH - dq_H dSig_G - q d2Sig_GH)/Sigma - dq_G * dSig_H / Sigma
        dq = (dPA - q * dSig) / Sigma
        # term1: dq_H * dSig_G  -> layout (G,a,H,b): einsum("hj,gi->gihj", dq, dSig)
        # term2: dq_G * dSig_H  -> layout (G,a,H,b): einsum("gi,hj->gihj", dq, dSig)
        d2q = (d2PA - np.einsum("hj,gi->gihj", dq, dSig) - q * d2Sig) / Sigma \
            - np.einsum("gi,hj->gihj", dq, dSig) / Sigma
        d2[:, :, :, :, g] = wb * d2q
    return d2


def becke_partition_dweight_d2A(mol, grids):
    """Interface: d2 w_g/dR_G dR_H, shape (M,3,M,3,N). Fills associated-atom rows
    for both derivative indices via translation invariance."""
    grid_coords = np.asarray(grids.coords, order="C")
    grid_weights = np.asarray(grids.quadrature_weights)
    atm_idx = np.asarray(grids.atm_idx)
    atm_coords = np.asarray(mol.atom_coords(), order="C")
    natm = mol.natm
    radii_adjust = grids.radii_adjust
    atomic_radii = grids.atomic_radii
    if callable(radii_adjust) and atomic_radii is not None:
        f_adj = radii_adjust(mol, atomic_radii)
        a_factor = np.array([f_adj(i, j, 0)
                             for i in range(natm) for j in range(natm)]
                            ).reshape(natm, natm)
    else:
        a_factor = np.zeros((natm, natm))
    d2 = becke_weight_derivative2_ref(grid_coords, grid_weights, atm_coords,
                                      a_factor, atm_idx)
    ngrids = grid_coords.shape[0]
    # eq (8) applied to second derivative index H (axis 2):
    #   d2[G,a,Ag,b,g] = -sum_H d2[G,a,H,b,g]   (Ag = atm_idx[g])
    sumH = -np.sum(d2, axis=2)                              # (M,3,3,N) = (G,a,b,g)
    for g in range(ngrids):
        Ag = int(atm_idx[g])
        if Ag >= 0:
            d2[:, :, Ag, :, g] = sumH[:, :, :, g]
    # eq (8) applied to first derivative index G (axis 0):
    #   d2[Ag,a,H,b,g] = -sum_G d2[G,a,H,b,g]
    sumG = -np.sum(d2, axis=0)                              # (3,M,3,N) = (a,H,b,g)
    for g in range(ngrids):
        Ag = int(atm_idx[g])
        if Ag >= 0:
            d2[Ag, :, :, :, g] = sumG[:, :, :, g]
    return d2


if __name__ == "__main__":
    mol, grids = get_mol_grids(XYZ0)
    d2_ref = numerical_d2weight_dAdB(XYZ0)
    d2_ana = becke_partition_dweight_d2A(mol, grids)
    mask = grids.atm_idx >= 0
    print("shapes:", d2_ref.shape, d2_ana.shape)
    for (A, a, B, b, lab) in [(0, 0, 0, 0, "0x0x"),
                              (0, 0, 0, 1, "0x0y"),
                              (0, 0, 1, 0, "0x1x")]:
        sr = d2_ref[A, a, B, b, mask]
        sa = d2_ana[A, a, B, b, mask]
        diff = np.abs(sr - sa)
        print(f"{lab}: max|ana|={np.max(np.abs(sa)):.4e} "
              f"max|diff|={np.max(diff):.4e} median|diff|={np.median(diff):.4e}")
